[package]
name = "alice"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chumsky = "0.9.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tsify = "0.4.5"
wasm-bindgen = "0.2.92"
