name: Automatic tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: cargo build
        run: cargo build --verbose
      - name: Run Rust tests
        run: cargo test --verbose
      - name: Build WASM Binary
        run: wasm-pack build
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Install npm packages
        run: npm i
        working-directory: frontend
      - name: Build frontend
        run: npm run build:prod
        working-directory: frontend